services:
  - type: web
    name: sih-vcad-3d-cadastre
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python server.py
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.9
